### ISSUE TITLE
Remove plug-in image due to racial insensitivity 

### ISSUE THREAD

**Issue by Matheus673** [klthelen/wake-up#1]
## Expected Behavior
Users should be able to view and use the plug-in without a sheep portraying "[blackface](https://en.wikipedia.org/wiki/Blackface)" being presented to them

## Actual Behavior
Upon viewing this repo or using the plug-in, users are greeted with a potentially upsetting image

## Steps to Reproduce the Problem

  1. Think to yourself "oh gee this sounds like a great plug-in let me try it"
  1. Add the repo to your collection or view the repository 
  1. Be shocked at the image you are met with

## Specifications

  - Version: Current master (8ce5dba2cf8b1e7fe995ff2ba6c79dd49d849de7)
  - Platform: All 
  - Subsystem: N/A

## Suggestions 
We should change this image to another normal sheep picture.

**Comment by klthelen** [comment]
Hi Matheus De Oliveira,

The image is not a sheep portraying blackface, but is actually an image of the [Valais Blacknose sheep](https://en.wikipedia.org/wiki/Valais_Blacknose). This sheep is often considered [the cutest sheep in the world](https://www.proquest.com/docview/1918278579?sourcetype=Newspapers)!

I hope this helps!
Kirk
